#!/usr/bin/env bash
#
# zsh aliases file: collection of all aliases

alias ls='ls --color=auto'
alias ll='ls -lha --group-directories-first'
alias lt='ls -lhat'
alias lr='ls -lhatr'

alias c='clear'

# copy to clip
alias copy='xclip -selection clipboard'

# k8s
alias k='kubectl'
alias kcn='kubectl config set-context --current --namespace'
alias kcx='kubectl config set-context'

# git
alias gst='git status --short'
alias gc='git commit --status --verbose'
alias ga='git add'
alias gp='git push'
alias gu='git pull'
