# Catppuccin Mocha Palette

# Catppuccin Mocha Palette
set -g @rosewater 'colour224' # #f5e0dc
set -g @flamingo 'colour217'  # #f2cdcd
set -g @pink 'colour212'      # #f5c2e7
set -g @mauve 'colour141'     # #cba6f7
set -g @red 'colour203'       # #f38ba8
set -g @maroon 'colour131'    # #eba0ac
set -g @peach 'colour209'     # #fab387
set -g @yellow 'colour180'    # #f9e2af
set -g @green 'colour114'     # #a6e3a1
set -g @teal 'colour115'      # #94e2d5
set -g @sky 'colour117'       # #89dceb
set -g @sapphire 'colour110'  # #74c7ec
set -g @blue 'colour111'      # #89b4fa
set -g @lavender 'colour183'  # #b4befe
set -g @text 'colour250'      # #cdd6f4
set -g @subtext1 'colour247'  # #bac2de
set -g @subtext0 'colour246'  # #a6adc8
set -g @overlay2 'colour243'  # #9399b2
set -g @overlay1 'colour242'  # #7f849c
set -g @overlay0 'colour240'  # #6c7086
set -g @surface2 'colour238'  # #585b70
set -g @surface1 'colour237'  # #45475a
set -g @surface0 'colour236'  # #313244
set -g @base 'colour235'      # #1e1e2e
set -g @mantle 'colour234'    # #181825
set -g @crust 'colour233'     # #11111b
