#!/usr/bin/env zsh
#
# zsh aliases file: collection of all zsh aliases

alias ls='ls --color=auto'
alias ll='ls -lha --group-directories-first'
alias lt='ls -lhat'
alias lr='ls -lhatr'

alias c='clear'

alias cp='xclip -selection clipboard'
alias p='xclip -o -selection clipboard'

alias k='kubectl'
alias kcn='kubectl config set-context --current --namespace'
alias kcx='kubectl config set-context'
