#!/usr/bin/env bash
#
# Get the current memory usage as percentage for tmux status

function _get_memory_usage() {
  local mem_total mem_available mem_usage using_percent

  mem_total="$(grep 'MemTotal' '/proc/meminfo' | awk '{print $2}')"
  mem_available="$(grep 'MemAvailable' '/proc/meminfo' | awk '{print $2}')"
  mem_usage="$(("${mem_total}" - "${mem_available}"))"
  using_percent="$(("${mem_usage}" * 100 / "${mem_total}" ))"

  printf '%s' "mem: ${using_percent}%"
}

function main() {
  _get_memory_usage
}

main
