#!/usr/bin/env bash
#
# Add all available SSH keys to the ssh-agent.

SSH_KEY_DIR="${HOME}/.ssh"

for key in "${SSH_KEY_DIR}"/*.pub; do
  printf "Adding SSH key: %s\n" "${key%.pub}"

  if [[ -f "${key%.pub}" ]]; then
    ssh-add "${key%.pub}"
  fi
done
