# ~~~~~ ZSH.rc Config ~~~~~ #

# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"


# History settings
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

# Enable completions of aliases
setopt completealiases

# Set zsh theme
ZSH_THEME="refined"

# set update behaviour of oh-my-zsh
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# List for oh-my-zsh plugins
plugins=(
    fzf
    fzf-tab
    zsh-autosuggestions
    zsh-syntax-highlighting
    terraform
)

# Source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Default applications
export BROWSER='chrome'

# Language
export LC_ALL=C.UTF-8

# ~~~ Custom Environment Variables ~~~ #
export GITHUB_USER='nocderechte'
export DOTFILES_DIR="$HOME/Repos/github.com/$GITHUB_USER/dotfiles"

# Add custom scripts to PATH
PATH=$PATH:$DOTFILES_DIR/scripts

# ~~~ Aliases ~~~ #
alias ls="ls --color"
alias ll="ls -lha --group-directories-first"
alias lt="ls -lhat"
alias lr="ls -lhatr"

alias c="clear"
alias cat="batcat" # always use better cat
alias cd="z" # always use zoxide instead of cd

alias -g -- --help='--help 2>&1 | cat --language=help --style=plain'
